#General Parameters
plugins:
  - {name: inflation, type: "costmap_2d::InflationLayer"}
  - {name: obstacle, type: "costmap_2d::ObstacleLayer"}
global_frame: /map
robot_base_frame: /base_link
transform_tolerance: 0.2

#Rate Parameters
update_frequency: 5.0
publish_frequency: 2.0

#Map Management Parameters
rolling_window: false
always_send_full_costmap: true

#Map Parameters
width: 100
height: 100
resolution: 0.05
origin_x: 0
origin_y: 0

#Obstacle Layer Parameters
obstacle:
  #Sensor Management Parameters
  observation_sources: ""
  topic: /scan
  sensor_frame: ""
  observation_persistence: 0
  expected_update_rate: 0
  data_type: "LaserScan"
  clearing: true
  marking: true
  max_obstacle_height: 2
  min_obstacle_height: 0
  obstacle_range: 20
  raytrace_range: 50
  inf_is_valid: true

  #Costmap Parameters
  track_unknown_space: true
  footprint_clearing_enabled: false

  
#Inflation Layer Parameters
inflation:
  inflation_radius: 0.55
  cost_scaling_factor: 0.1